# Generated by Django 4.2.7 on 2023-11-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', through='calendar_app.JoinEventCategory', to='calendar_app.eventscategory'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='categories',
            field=models.ManyToManyField(related_name='templates', through='calendar_app.JoinTemplateCategory', to='calendar_app.eventscategory'),
        ),
        migrations.AlterUniqueTogether(
            name='joineventcategory',
            unique_together={('event', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='jointemplatecategory',
            unique_together={('template', 'category')},
        ),
    ]
